name: Build and Test

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:3.11
    services:
      postgres:
        image: postgres:15.12
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install
          playwright install-deps
      
      - name: Run tests and check coverage
        env: 
          TEST_DATABASE: test_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: postgres
          DB_PORT: 5432
        run: |
          coverage run -m pytest
          coverage report --fail-under=80
      
